### ISSUE TITLE
(定率割引)クーポン適用後に複数配送で商品数量が変更になった場合、値引き額が再計算されない。

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/coupon-plugin#101]
## 概要
クーポン適用後に複数配送で商品数量が変更になった場合に、クーポンによる値引き額が再計算されない。

## 期待結果
複数配送の設定後は、最新の購入商品情報でクーポンの値引き額が更新されること。

### クーポンの設定
対象商品：全商品
値引き種別：定率割引
※その他は任意の有効なクーポンを作成する

### 手順
1. 商品をカートに入れて購入ページに進む。
1. クーポンを適用する。
1. [お届け先を追加する]ボタンからお届け先と商品数を複数に変更する。
1. 購入ページに戻り値引き額を確認する。
→値引き額が更新されない(NG)

**Comment by nanasess** [comment]
カートに戻って数量変更すると、クーポンが初期化されますが、複数配送設定画面で数量変更した場合は初期化されません。
プラグインの仕様上、クーポンを初期化するようカート画面に合わせた方が良いと思われます。

**Comment by kazumiiiiiiiiiii** [comment]
@nanasess ありがとうございます。
複数配送設定で、数量を変更するとクーポンを利用する設定が初期化することを確認しました。

<img width="1105" alt="スクリーンショット 2019-07-19 16 57 53" src="https://user-images.githubusercontent.com/34618717/61519348-aab60900-aa46-11e9-8bae-db053c9223ce.png">
