### ISSUE TITLE
(定率割引)複数配送先に分かれている場合、すべての配送先の合計金額で値引き額が計算されていない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/coupon-plugin#102]
## 概要
複数配送先に分かれている場合、すべての配送先の合計金額でクーポンの値引き額が計算されていない

## 期待結果
すべての配送先の商品を対象に、クーポンの値引き額が設定されること。

### クーポンの設定
対象商品：全商品
値引き種別：定率割引
※その他の設定は任意で、有効なクーポンを作成する

### 手順
1. 商品をカートに入れて購入ページに進む。
1. [お届け先を追加する]ボタンからお届け先と商品数を複数に変更する。
(お届け先ごとに商品数を変更しておくと事象がわかりやすい)
1. クーポンを適用する。
1. 値引き額を確認する。
→値引き額が、すべての配送先の商品合計から計算した金額と異なっている(NG)
※片方の配送先の金額から計算しているように見える

**Comment by kazumiiiiiiiiiii** [comment]
@nanasess ありがとうございます。
#105 で不具合の解消を確認しました。
