### ISSUE TITLE
クーポン適用後に複数配送画面で最低購入金額以下に商品数を変更した場合に、値引きが消えない

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/coupon-plugin#103]
## 概要
クーポン適用後、複数配送画面で最低購入金額以下に商品数を変更した場合に、クーポンによる値引きが消えない。

## 期待結果
クーポンが適用不可のため、クーポンによる値引きが削除されること。

### クーポンの設定
対象商品：全商品
値引き種別：定額割引
最低購入額：9000円
※その他は任意の有効なクーポンを作成する

### 手順
1. チェリーアイスサンドを3つカートに入れて購入ページに進む。(約9000円)
1. クーポンを適用する。
1. [お届け先を追加する]ボタンからチェリーアイスサンドの購入数を1つにする。(約3000円)
1. 購入ページに戻り値引き額を確認する。
→クーポンは警告メッセージともに非適用の状態になっている(OK)
→値引き額が消えていない(NG)

## 発生時の画面キャプチャ
![image](https://user-images.githubusercontent.com/16891862/60855767-fcd57e00-a23f-11e9-9623-a5c136ce8445.png)

**Comment by kazumiiiiiiiiiii** [comment]
ありがとうございます。
不具合の修正を確認いたしました。
