### ISSUE TITLE
有効期間が有効値ではありませんって

### ISSUE THREAD

**Issue by juvenchamp** [EC-CUBE/coupon-plugin#125]
![29B860ED-2CAC-4857-940C-35B55D088493](https://user-images.githubusercontent.com/62980394/78121842-781a3800-743e-11ea-8cf6-229c16f83d7d.png)
クーポン発行画面にエラーメッセージが出てきました。
有効期間が有効値ではありませんって
An error message has appeared on the coupon issue screen.
The validity period is not a valid value, I set the validity period like this:2020/03/29 ~2020/04/30

**Comment by chihiro-adachi** [comment]
ver4.0.7で確認したところ、再現を確認できませんでした。
Mac safari/chrome/firefoxで確認しています。

おそらく修正済かとおもいますのでクローズします。
