### ISSUE TITLE
同じユーザは二つBrowserで同じクーポンで利用できる

### ISSUE THREAD

**Issue by lammn** [EC-CUBE/coupon-plugin#21]
## 現象
同じユーザは二つBrowserで同じクーポンで利用できる

## 再現手順

1. Chromeでログインして注文確認画面まで行きます。

2. IEで同じユーザをログインして注文確認画面も行きます。

3. 同時に注文するボタンをクリックする

　=> 注文完了画面に移動して、同じユーザは同じクーポンで利用できる（ＮＧ）

## 期待値
同じユーザは一回しか利用できない。

**Comment by chihiro-adachi** [comment]
#28 で対応

**Comment by lammn** [comment]
クレジットカード決済なら、以上のような、出来てしまいました。
