### ISSUE TITLE
クーポン適用の最低金額を設定できるようにする

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/coupon-plugin#54]
クーポン適用の最低金額を設定できるようにします。

### 仕様
カートの中にあるクーポン対象商品が、１つでも最低金額を超えていれば利用可能。
※合計ではなく対象商品１つの単価が、最低金額を超えていること。

### Sample
商品A:100円
商品B：1000円
商品C：1000円

クーポン：
　最低金額＝500円
　対象商品＝商品A,商品B

#### パターン①
カート：商品B,C
結果：適用OK

#### パターン②
カート：商品A
結果：適用NG（最低金額を超えていないため）

#### パターン③
カート：商品A,C
結果：適用NG（対象商品が最低金額を超えていないため）

#### パターン④
カート：商品A x 5個
結果：適用NG（対象商品の単価が最低金額を超えていないため）

**Comment by ryo-endo** [comment]
> ※合計ではなく対象商品１つの単価が、最低金額を超えていること。
※(全商品の合計ではなく)対象商品の合計が最低金額を超えていること。

**Comment by lammn** [comment]
パターン⑤
カート：商品A,B, C
結果：適用NG（対象商品が最低金額を超えていないため）
これは正しいですか。今の考えるのは一つ商品は最低金額を超えていない場合はNGになります。

パターン⑥
カート：商品A x 5個,B, C
結果：適用OK, 各商品の小計はOKだから。

ご確認お願いします。

**Comment by ryo-endo** [comment]
設定としては、合計500円以上で500円割引みたいなクーポンも設定はできるが、実際にお店はこんな設定はしない想定とする。

**Comment by ryo-endo** [comment]
そのため...

パターン⑤
カート：商品A,B,C
結果：適用OK（対象商品A+B=1100円 >= 最低金額500円 なので）

パターン⑥
カート：商品A x 5個,B, C
結果：適用OK(対象商品Ax5+B=1500円 >= 最低金額500円 なので）

**Comment by ryo-endo** [comment]
v.2.0.0で、上記内容で対応済み。
