### ISSUE TITLE
クーポン登録画面の商品/カテゴリ検索をページングに対応する

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/coupon-plugin#55]
クーポン登録画面
商品/カテゴリ検索するモーダルウィンドウをページングに対応する。

**Comment by t-nagahashi** [comment]
カテゴリ検索は、そもそも検索の形でよいのでしょうか？
受注編集のようなカテゴリ選択にすべきのようにも感じます。

**Comment by ryo-endo** [comment]
@t-nagahashi 
別途、Issueをお願いします。

**Comment by ryo-endo** [comment]
ページングについては、v.2.0.0で対応済み。
