### ISSUE TITLE
クーポン登録/編集時のフォームに文言が正しく表示されない

### ISSUE THREAD

**Issue by kazumiiiiiiiiiii** [EC-CUBE/coupon-plugin#82]
## 概要(Overview)

クーポン登録/編集時の、selectの初期値や追加する際のボタン、削除時のボタンの文字が正しく表示されていない

## 期待する内容(Expect)  or 要望 (Requirement)

フォームのselectの初期値と、追加する際のボタン、削除時のボタンの文字が表示が正しく表示されていること

#### フォームのselectの初期値の手順
1. 管理画面「受注管理/クーポン」から「クーポンを新規登録」
2. 「対象商品」を「カテゴリ」に変更し、「カテゴリ情報」から「カテゴリの追加」

<img width="614" alt="スクリーンショット 2019-06-17 17 23 10" src="https://user-images.githubusercontent.com/34618717/59589335-a4b9c900-9124-11e9-92c2-67069f2a97ba.png">

#### 追加する際のボタンの手順
1. 管理画面「受注管理/クーポン」から「クーポンを新規登録」
2. 「対象商品」を「商品」に変更し、「商品情報」から「商品の追加」
3. 表示される検索画面で「検索」

<img width="609" alt="スクリーンショット 2019-06-17 17 23 22" src="https://user-images.githubusercontent.com/34618717/59589338-a5eaf600-9124-11e9-9b01-4ddf6411cb82.png">

※ 「対象商品」が「カテゴリ」の場合も同様

#### 削除時のボタンの手順
1. 管理画面「受注管理/クーポン」から「対象商品」を「商品」で、「商品情報」に商品を追加しクーポンを登録
2. 管理画面「受注管理/クーポン」からクーポン一覧を表示し、「編集」

<img width="789" alt="スクリーンショット 2019-06-17 17 37 08" src="https://user-images.githubusercontent.com/34618717/59590240-910f6200-9126-11e9-9c0e-903c7f8e5450.png">

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by nanasess** [comment]
修正しました
https://github.com/EC-CUBE/coupon-plugin/pull/77/commits/b6cb5a802829c83de08daf9607899ecce9b8b64e

**Comment by junpeko5** [comment]
#77
で対応済み
