### ISSUE TITLE
クーポンの「有効/無効」切り替え時のconfirmメッセージが正しくない

### ISSUE THREAD

**Issue by kazumiiiiiiiiiii** [EC-CUBE/coupon-plugin#83]
## 概要(Overview)

クーポンの「有効/無効」切り替え時のconfirmメッセージが削除を行う確認メッセージとなっている

## 期待する内容(Expect)  or 要望 (Requirement)

クーポンの「有効/無効」切り替え時のconfirmメッセージが正しい文言のメッセージとなっていること

## 再現手順(Procedure)

1. 管理画面「受注管理/クーポン」から「クーポンを新規登録」
2. 管理画面「受注管理/クーポン」からクーポンの一覧画面を表示
2. 「状態」のカラムから「有効/無効」を切り替える

<img width="456" alt="※3" src="https://user-images.githubusercontent.com/34618717/59590880-edbf4c80-9127-11e9-8c88-7d9a68179c7b.png">

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by nanasess** [comment]
修正しました 6c581ba

**Comment by nanasess** [comment]
修正しました 6c581ba

**Comment by junpeko5** [comment]
#77
で対応済み
