### ISSUE TITLE
クーポン編集時の金額入力時に小数点が現れてしまう。

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/coupon-plugin#84]
## 概要(Overview)

クーポン編集時、「値引き額(円)」、「下限金額(円)」を入力するテキストボックスに小数点が表示されてしまう。

## 期待する内容(Expect)  or 要望 (Requirement)

小数点は表示されず、正の整数で表示されること。

## 再現手順(Procedure)

1.  管理画面/クーポン一覧より、「受注管理/クーポン」から「クーポンを新規登録」。
2. 管理画面/クーポン一覧より、編集リンクを押下。

<img width="1105" alt="スクリーンショット 2019-06-17 17 50 26" src="https://user-images.githubusercontent.com/26207848/59591137-70e0a280-9128-11e9-8ae7-a84b51e3425a.png">

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by nanasess** [comment]
修正しました d898657

**Comment by junpeko5** [comment]
#77
で対応済み
