### ISSUE TITLE
ご注文手続き画面でクーポンを２回登録して注文するとメールのクーポン項目が２つになる

### ISSUE THREAD

**Issue by kazumiiiiiiiiiii** [EC-CUBE/coupon-plugin#85]
## 概要(Overview)

「ご注文手続き」画面で「クーポンを変更」から２回登録して注文するとメールの「クーポン情報 」の項目が２つ表示される

## 期待する内容(Expect)  or 要望 (Requirement)

「ご注文手続き」画面で「クーポンを変更」から２回登録しても、メールの「クーポン情報 」の項目は１つしか表示されないこと

## 再現手順(Procedure)

1. 管理画面「受注管理/クーポン」からクーポンを登録
2. 登録したクーポンを使用できる条件で、フロント画面で商品購入を「ご注文手続き」まで進める
3. 「クーポンを変更する」から「クーポンを利用する」「クーポンコード」を入力し「登録する」
4. 「ご注文手続き」画面に戻ったら再度、「クーポンを変更する」から「クーポンを利用する」「クーポンコード」を入力し「登録する」
5. 注文完了まで進み「マイページ/ご注文履歴」から「ご注文履歴詳細」を表示する
6. 「メール配信履歴一覧」から配信内容を確認する

<img width="599" alt="スクリーンショット 2019-06-17 18 08 15" src="https://user-images.githubusercontent.com/34618717/59592387-ebaabd00-912a-11e9-84ae-215cc8bf6594.png">
※ 手順「4」を繰り返した分表示されるようです。

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by nanasess** [comment]
修正しました 29879d8

**Comment by junpeko5** [comment]
#77
で対応済み
