### ISSUE TITLE
値引き種別：値引き率で購入時、値引き率が値引き対象の商品全てに適用されない

### ISSUE THREAD

**Issue by junpeko5** [EC-CUBE/coupon-plugin#86]
## 概要(Overview)

値引き種別：値引き率で購入時、値引き額が１商品のみに適用される。

## 期待する内容(Expect)  or 要望 (Requirement)

値引き対象の商品全てに適用されること

## 再現手順(Procedure)

1. 管理画面「受注管理/クーポン」から「クーポンを新規登録」
今回管理画面より登録したクーポンの設定内容
```
対象商品：商品
利用制限：なし
値引き種別：値引率
値引率（％）:10
発行枚数：3
下限金額（円）：0に変更
商品：チェリーアイス、彩のジェラートCUBE
```
2. フロント画面で値引き対象商品を複数カートに入れ、ご注文手続き画面に進む。
3. 「クーポンの変更」よりクーポンを適用する。

<img width="1198" alt="スクリーンショット 2019-06-17 18 10 06" src="https://user-images.githubusercontent.com/26207848/59592604-5825bc00-912b-11e9-982a-09cb32905238.png">

### 環境 (environment)
+ EC-CUBE: 4.0.2

**Comment by nanasess** [comment]
修正しました 5313afd

**Comment by junpeko5** [comment]
#77
で対応済み
